version: '3.9'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: greenwich_micro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@greenwich.edu
      PGADMIN_DEFAULT_PASSWORD: secret
    ports:
      - '5051:80'
    depends_on:
      postgres:
        condition: service_healthy
volumes:
  postgres_data:
